trigger:
- main

pool: "self-hosted"
variables:
  - group: Black Duck

steps:
- task: BlackDuckSecurityScan@2.0.0
  displayName: 'Black Duck Full Scan'
  condition: not(eq(variables['Build.Reason'], 'PullRequest'))
  env:
    DETECT_PROJECT_NAME: az-$(Build.Repository.Name)
  inputs:
    BLACKDUCKSCA_URL: $(BLACKDUCKSCA_URL)
    BLACKDUCKSCA_TOKEN: $(BLACKDUCKSCA_TOKEN)
    BLACKDUCKSCASCA_SCAN_FULL: false
    BLACKDUCKSCA_WAITFORSCAN: true 
    DETECT_SEARCH_DEPTH: 4
    DETECT_ARGS: '--blackduck.trust.cert=true --detect.diagnostic=true --detect.accuracy.required=NONE --detect.logging=DEBUG'
    continueOnError: false   
