name: Synopsys

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: [ ubuntu-latest ]
    #permissions:
    #  contents: write
    steps:
      - name: GET Sigma Tools
        run: |
          mkdir -p /opt/blackduck/hub/uploads/tools/sigma/
          curl -o /opt/blackduck/hub/uploads/tools/sigma/2024.6.1_linux_x86_64  https://sig-repo.synopsys.com/artifactory/sigma-release-trial/2024.6.1/sigma-linux_x86_64
          chmod +x /opt/blackduck/hub/uploads/tools/sigma/2024.6.1_linux_x86_64
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Synopsys Application Security Testing
        if: ${{ github.event_name != 'pull_request' }}   
        uses: synopsys-sig/synopsys-action@v1.10.0
        with:
          blackduck_url: ${{ vars.BLACKDUCK_URL }}
          blackduck_token: ${{ secrets.BLACKDUCK_TOKEN }}
          blackduck_scan_failure_severities: 'BLOCKER,CRITICAL'
          blackduck_args: '--detect.diagnostic=true --detect.project.name=tomcat-9.0.41 --detect.tools=DETECTOR --detect.excluded.detector.types=GIT'
          blackduck_scan_full: 'true'
          blackduck_search_depth: 4
          blackduck_upload_sarif_report: true
          blackduck_reports_sarif_create: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
        env:
          BLACKDUCK_TRUST_CERT: false
          DETECT_LATEST_RELEASE_VERSION: 9.5.0
      - name: Copy Output
        run: |
          cp /home/runner/work/tomcat-9.0.41/tomcat-9.0.41/.bridge/"Blackduck SARIF Generator"/report.sarif.json ${{ github.workspace }}report.sarif.json
      - uses: actions/upload-artifact@v4
        with:
          name: report.sarif.json
          path: ${{ github.workspace }}report.sarif.json
          compression-level: 0 # no compression    
