name: Synopsys

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [self-hosted]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Synopsys Application Security Testing
        uses: synopsys-sig/synopsys-action@main
        with:
          synopsys_bridge_path: /tmp/synopsys-bridge
          bridge_download_url: ${{ env.LINUX_BRIDGE_URL }}
          blackduck_install_directory: /tmp/synopsys-bridge/blackduck/8.0.0
          blackduck_url: ${{ secrets.BLACKDUCK_URL }}
          blackduck_apiToken: ${{ secrets.BLACKDUCK_API_KEY }}
          blackduck_scan_full: true
          blackduck_automation_fixpr: true
          blackduck_prComment_enabled: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          #blackduck_scan_failure_severities: "['ALL']"
          #coverity_url: ${{ secrets.COVERITY_URL }}
          #coverity_user: ${{ secrets.COVERITY_USER }}
          #coverity_passphrase: ${{ secrets.COVERITY_PASSPHRASE }}
          #coverity_project_name: ${{ github.event.repository.name }}
          #coverity_stream_name: ${{ github.event.repository.name }}
          #polaris_serverUrl: ${{ secrets.POLARIS_SERVER_URL }}
          #polaris_accessToken: ${{ secrets.POLARIS_ACCESS_TOKEN }}
          #polaris_application_name: "SUGA-Testing-WebGoat"
          #polaris_project_name: "SUGA-Testing-WebGoat"
          #polaris_assessment_types: '["SAST", "SCA"]'
        env:
          BLACKDUCK_TRUST_CERT: true
          NODE_TLS_REJECT_UNAUTHORIZED: 0
          LINUX_BRIDGE_URL: "https://artifactory.internal.synopsys.com/artifactory/clops-local/clops.sig.synopsys.com/synopsys-bridge/latest/synopsys-bridge-macos_arm.zip"
