name: Synopsys

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: [ ubuntu-latest ]
    #permissions:
    #  contents: write
    steps:
      - name: GET Sigma Tools
        run: |
          mkdir -p /opt/blackduck/hub/uploads/tools/sigma/
          curl -o /opt/blackduck/hub/uploads/tools/sigma/2024.6.1_linux_x86_64  https://sig-repo.synopsys.com/artifactory/sigma-release-trial/2024.6.1/sigma-linux_x86_64
          chmod +x /opt/blackduck/hub/uploads/tools/sigma/2024.6.1_linux_x86_64
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Synopsys Application Security Testing
        if: ${{ github.event_name != 'pull_request' }}
        uses: synopsys-sig/synopsys-action@v1.10.0
        with:
          blackduck_url: ${{ vars.BLACKDUCK_URL }}
          blackduck_token: ${{ secrets.BLACKDUCK_TOKEN }}
          blackduck_scan_failure_severities: 'BLOCKER,CRITICAL'
          blackduck_args: '--detect.diagnostic=true --detect.project.name=workflow-iac --detect.tools=IAC_SCAN --detect.excluded.detector.types=GIT --detect.iac.scanner.local.path=/opt/blackduck/hub/uploads/tools/sigma/2024.6.1_linux_x86_64'
          blackduck_scan_full: 'true'
          blackduck_search_depth: 4
          blackduck_upload_sarif_report: false
          blackduck_reports_sarif_create: false
          github_token: ${{ secrets.GITHUB_TOKEN }}
        env:
          BLACKDUCK_TRUST_CERT: false
